### ISSUE TITLE
Many issues 

### ISSUE THREAD

**Issue by munger100** [asaini/Apriori#11]
No python3 optimization: `print value` should be `print(value)`... and you try to use indexing in dictionaries which will give errors.

**Comment by sn1p3r46** [comment]
@munger100 see this pull request, maybe can help you https://github.com/asaini/Apriori/pull/3

**Comment by Dawny33** [comment]
@sn1p3r46 Shouldn't this be closed long back? `Solution: Use the Python 2to3 tool`

**Comment by sn1p3r46** [comment]
@Dawny33 I am not the owner of the repo.
