### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by asaini** [asaini/Apriori#17]
I've created a new `python3` branch to start supporting the code in both 2.7 and 3.4. In the coming days I'll be doing some work to add python3 support

**Comment by alonsopg** [comment]
Thanks, could you provide a jupyter notebook with examples?.

**Comment by foo123** [comment]
any news on this?

**Comment by rashmisrao** [comment]
unable to run the file on python 3.Can you help ?

**Comment by asaini** [comment]
Closing. Script now supports python3 after #27
