### ISSUE TITLE
Invalid syntax: `key=lambda (item,`

### ISSUE THREAD

**Issue by jacolind** [asaini/Apriori#22]
I ran this inside my jupyter notebook and got the following error 

```
Title "<ipython-input-303-3f4dffe6b184>", line 118
    for item, support in sorted(items, key=lambda (item, support): support):
                                                 ^
SyntaxError: invalid syntax

```

**Comment by AnthonyNTK** [comment]
Run the script with python 2.7 or you can use python2to3.exe to convert the script to be python3 compatible. Jupyter is using 3.6 or higher
