### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by slchen2014** [asaini/Apriori#9]
I want to use [Sourcegraph](https://sourcegraph.com) for Apriori code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/asaini/Apriori. (It should only take 30 seconds.)

Thank you!

**Comment by valeIT** [comment]
just branch and do it yourself, it's mit. ;)

**Comment by asaini** [comment]
Closing this issue. As the comment above suggests, you can Fork and enable Sourcegraph on your forked version.
